version: "3.7"

services:
  jenkins:
    build: .  #image: jenkins/jenkins:lts, but we added docker client
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "jenkins_home:/var/jenkins_home"
    ports:
      - '8080:8080'
      - '50000:50000'
volumes:
   jenkins_home:
